# Generated by Django 5.2.6 on 2025-10-04 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defensivezoneexit',
            old_name='skate',
            new_name='skate_out',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='arena_rink',
            new_name='rink',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='gameevents',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RenameField(
            model_name='offensivezoneentry',
            old_name='dump_l',
            new_name='dump_lose',
        ),
        migrations.RenameField(
            model_name='offensivezoneentry',
            old_name='dump_w',
            new_name='dump_win',
        ),
        migrations.RenameField(
            model_name='offensivezoneentry',
            old_name='passes',
            new_name='pass_in',
        ),
        migrations.RenameField(
            model_name='offensivezoneentry',
            old_name='skate',
            new_name='skate_in',
        ),
        migrations.RenameField(
            model_name='shots',
            old_name='scoring_chances',
            new_name='scoring_chance',
        ),
        migrations.RemoveField(
            model_name='gameevents',
            name='player',
        ),
        migrations.AddField(
            model_name='game',
            name='away_team_goalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='away_games', to='hockey.goalie'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team_goalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_games', to='hockey.goalie'),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='players',
            field=models.ManyToManyField(to='hockey.player'),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='YouTube Link'),
        ),
        migrations.AlterField(
            model_name='goalietransaction',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.teamlevel'),
        ),
    ]
