# Generated by Django 5.2.6 on 2025-10-06 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0002_rename_skate_defensivezoneexit_skate_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'seasons',
            },
        ),
        migrations.AlterField(
            model_name='goalietransaction',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.season'),
        ),
        migrations.AlterField(
            model_name='playertransaction',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.season'),
        ),
        migrations.AlterField(
            model_name='teamseason',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.season'),
        ),
    ]
