# Generated by Django 5.2.6 on 2025-10-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0003_season_alter_goalietransaction_season_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'city'), name='unique_team'),
        ),
    ]
