# Generated by Django 5.2.6 on 2025-10-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0004_team_unique_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalie',
            name='saves_above_avg',
            field=models.IntegerField(default=0),
        ),
    ]
