# Generated by Django 5.2.6 on 2025-10-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0005_alter_goalie_saves_above_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defensivezoneexit',
            name='icing',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defensivezoneexit',
            name='passes',
            field=models.IntegerField(default=0, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='defensivezoneexit',
            name='skate_out',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='defensivezoneexit',
            name='so_lose',
            field=models.IntegerField(default=0, verbose_name='SO & Lose'),
        ),
        migrations.AlterField(
            model_name='defensivezoneexit',
            name='so_win',
            field=models.IntegerField(default=0, verbose_name='SO & Win'),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_faceoff_win',
            field=models.IntegerField(blank=True, null=True, verbose_name='Away Faceoff Win %'),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameperiod'),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_faceoff_win',
            field=models.IntegerField(blank=True, null=True, verbose_name='Home Faceoff Win %'),
        ),
        migrations.AlterField(
            model_name='offensivezoneentry',
            name='dump_lose',
            field=models.IntegerField(default=0, verbose_name='Dump/L'),
        ),
        migrations.AlterField(
            model_name='offensivezoneentry',
            name='dump_win',
            field=models.IntegerField(default=0, verbose_name='Dump/W'),
        ),
        migrations.AlterField(
            model_name='offensivezoneentry',
            name='pass_in',
            field=models.IntegerField(default=0, verbose_name='Pass'),
        ),
        migrations.AlterField(
            model_name='offensivezoneentry',
            name='skate_in',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shots',
            name='blocked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shots',
            name='missed_net',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shots',
            name='scoring_chance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shots',
            name='shots_on_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turnovers',
            name='def_zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turnovers',
            name='neutral_zone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='turnovers',
            name='off_zone',
            field=models.IntegerField(default=0),
        ),
    ]
