# Generated by Django 5.2.6 on 2025-10-16 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0006_alter_defensivezoneexit_icing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevents',
            name='event_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameeventname'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='goalie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.goalie'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='ice_left_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='ice_top_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='net_left_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='net_top_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamegoalie',
            name='goals_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamegoalie',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='assists',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='shots',
            field=models.IntegerField(default=0),
        ),
    ]
