# Generated by Django 5.2.6 on 2025-10-19 18:15

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0007_alter_gameevents_event_name_alter_gameevents_goalie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='penalties_taken',
        ),
        migrations.AddField(
            model_name='goalie',
            name='address_city',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='address_country',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='address_region',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthplace_city',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthplace_country',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='birthplace_region',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='penalty_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalie',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='goalie_photo/'),
        ),
        migrations.AddField(
            model_name='goalie',
            name='player_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='save_percents',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(games_played__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('saves'), '/', django.db.models.expressions.CombinedExpression(models.F('saves'), '+', models.F('goals_against'))), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Save %'),
        ),
        migrations.AddField(
            model_name='player',
            name='address_city',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='address_country',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='address_region',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='birthplace_city',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='birthplace_country',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='birthplace_region',
            field=models.CharField(default='?', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='faceoffs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='faceoffs_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='penalty_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='player_photo/'),
        ),
        migrations.AddField(
            model_name='player',
            name='player_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='power_play_goals',
            field=models.IntegerField(default=0, verbose_name='PPG'),
        ),
        migrations.AddField(
            model_name='player',
            name='short_handed_goals',
            field=models.IntegerField(default=0, verbose_name='SHG'),
        ),
        migrations.AddField(
            model_name='player',
            name='turnovers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='away_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='YouTube Link'),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='penalties_drawn',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='faceoff_win_percents',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(games_played__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('faceoffs_won'), '/', models.F('faceoffs')), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Faceoff Win %'),
        ),
    ]
