# Generated by Django 5.2.6 on 2025-10-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0008_remove_player_penalties_taken_goalie_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='position',
        ),
        migrations.AlterField(
            model_name='goalie',
            name='height',
            field=models.IntegerField(verbose_name='Height, inches'),
        ),
        migrations.AlterField(
            model_name='goalie',
            name='weight',
            field=models.IntegerField(verbose_name='Weight, lbs'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(verbose_name='Height, inches'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(verbose_name='Weight, lbs'),
        ),
    ]
