# Generated by Django 5.2.6 on 2025-10-21 20:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0010_goalieseason_playerseason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevents',
            name='players',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='penalty_minutes',
        ),
        migrations.RemoveField(
            model_name='goalieseason',
            name='penalty_minutes',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalties_drawn',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalty_minutes',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='penalties_drawn',
        ),
        migrations.RemoveField(
            model_name='playerseason',
            name='penalty_minutes',
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.season'),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='is_deprecated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player', to='hockey.player'),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='player_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_2', to='hockey.player'),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='time_length',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='penalty_minutes_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='goalieseason',
            name='penalty_minutes_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='player',
            name='penalties_drawn_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='player',
            name='penalty_minutes_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='penalties_drawn_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='playerseason',
            name='penalty_minutes_tmp',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.CreateModel(
            name='GameEventsAnalysisQueue',
            fields=[
                ('pk', models.CompositePrimaryKey('game_event_id', 'date_time', blank=True, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField()),
                ('game_event', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameevents')),
            ],
            options={
                'db_table': 'game_events_analysis_queue',
            },
        ),
    ]
