# Generated by Django 5.2.6 on 2025-10-21 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0011_remove_gameevents_players_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalie',
            old_name='penalty_minutes_tmp',
            new_name='penalty_minutes',
        ),
        migrations.RenameField(
            model_name='goalieseason',
            old_name='penalty_minutes_tmp',
            new_name='penalty_minutes',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='penalties_drawn_tmp',
            new_name='penalties_drawn',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='penalty_minutes_tmp',
            new_name='penalty_minutes',
        ),
        migrations.RenameField(
            model_name='playerseason',
            old_name='penalties_drawn_tmp',
            new_name='penalties_drawn',
        ),
        migrations.RenameField(
            model_name='playerseason',
            old_name='penalty_minutes_tmp',
            new_name='penalty_minutes',
        ),
    ]
