# Generated by Django 5.2.6 on 2025-10-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0012_rename_penalty_minutes_tmp_goalie_penalty_minutes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
