# Generated by Django 5.2.6 on 2025-10-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0013_alter_season_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalie',
            name='birthplace_city',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birthplace_region',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birthplace_city',
        ),
        migrations.RemoveField(
            model_name='player',
            name='birthplace_region',
        ),
        migrations.AddField(
            model_name='gameevents',
            name='is_faceoff_won',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goalie',
            name='address_postal_code',
            field=models.CharField(default='?', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalie',
            name='address_street',
            field=models.TextField(default='?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='address_postal_code',
            field=models.CharField(default='?', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='address_street',
            field=models.TextField(default='?'),
            preserve_default=False,
        ),
    ]
