# Generated by Django 5.2.6 on 2025-10-23 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0015_rename_shots_gameplayer_shots_on_goal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEventsAnalysisQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('action', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.game')),
                ('game_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameevents')),
            ],
            options={
                'db_table': 'game_events_analysis_queue',
                'constraints': [models.UniqueConstraint(fields=('game_event', 'game', 'action'), name='unique_game_event_game_action')],
            },
        ),
    ]
