# Generated by Django 5.2.6 on 2025-10-27 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0016_gameeventsanalysisqueue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegoalie',
            name='save_percents',
        ),
        migrations.RemoveField(
            model_name='gamegoalie',
            name='shots_against',
        ),
    ]
