# Generated by Django 5.2.6 on 2025-10-27 10:41

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0017_remove_gamegoalie_save_percents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoalie',
            name='save_percents',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(goals_against__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('saves'), '/', django.db.models.expressions.CombinedExpression(models.F('goals_against'), '+', models.F('saves'))), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Save %'),
        ),
        migrations.AddField(
            model_name='gamegoalie',
            name='shots_against',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('goals_against'), '+', models.F('saves')), output_field=models.IntegerField()),
        ),
    ]
