# Generated by Django 5.2.6 on 2025-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0018_gamegoalie_save_percents_gamegoalie_shots_against'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateField(default='2025-10-01'),
            preserve_default=False,
        ),
    ]
