# Generated by Django 5.2.6 on 2025-10-28 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0019_season_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightReel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('created_by', models.IntegerField()),
            ],
            options={
                'db_table': 'highlight_reels',
            },
        ),
        migrations.CreateModel(
            name='ShotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'shot_types',
            },
        ),
        migrations.AddField(
            model_name='gameevents',
            name='is_scoring_chance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shots',
            name='saves',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='shot_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.shottype'),
        ),
    ]
