# Generated by Django 5.2.6 on 2025-10-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0020_highlightreel_shottype_gameevents_is_scoring_chance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevents',
            name='zone',
            field=models.CharField(blank=True, choices=[('Attacking', 'Attacking'), ('Neutral', 'Neutral'), ('Defending', 'Defending')], max_length=20, null=True),
        ),
    ]
