# Generated by Django 5.2.6 on 2025-10-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0021_gameevents_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_faceoff_win',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_faceoff_win',
        ),
        migrations.AddField(
            model_name='game',
            name='faceoffs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_faceoffs_won_count',
            field=models.IntegerField(default=0),
        ),
    ]
