# Generated by Django 5.2.6 on 2025-10-30 17:46

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0022_remove_game_away_faceoff_win_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_faceoff_win',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(faceoffs_count__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('faceoffs_count'), '-', models.F('home_faceoffs_won_count')), '/', models.F('faceoffs_count')), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Away Faceoff Win %'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_faceoff_win',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(faceoffs_count__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('home_faceoffs_won_count'), '/', models.F('faceoffs_count')), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Home Faceoff Win %'),
        ),
    ]
