# Generated by Django 5.2.6 on 2025-10-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0023_game_away_faceoff_win_game_home_faceoff_win'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_faceoff_win',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_faceoff_win',
        ),
        migrations.AddField(
            model_name='game',
            name='away_shots_on_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='home_shots_on_goal',
            field=models.IntegerField(default=0),
        ),
    ]
