# Generated by Django 5.2.6 on 2025-10-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0024_remove_game_away_faceoff_win_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameevents',
            name='is_scoring_chance',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
