# Generated by Django 5.2.6 on 2025-10-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0025_alter_gameevents_is_scoring_chance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_shots_on_goal',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_shots_on_goal',
        ),
    ]
