# Generated by Django 5.2.6 on 2025-11-02 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0026_remove_game_away_shots_on_goal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='away_team_goalie',
        ),
        migrations.RemoveField(
            model_name='game',
            name='home_team_goalie',
        ),
        migrations.RemoveField(
            model_name='gameevents',
            name='zone',
        ),
        migrations.AddField(
            model_name='gameevents',
            name='goal_type',
            field=models.IntegerField(choices=[(2, 'Normal'), (3, 'Power Play'), (1, 'Short Handed')], default=2),
        ),
        migrations.AddField(
            model_name='gamegoalie',
            name='start_period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameperiod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gamegoalie',
            name='start_time',
            field=models.TimeField(default='0:00:00', verbose_name='Game time when the goalie started playing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(2, 'Game in Progress'), (3, 'Game Over'), (1, 'Not Started')], default=1),
        ),
    ]
