# Generated by Django 5.2.6 on 2025-11-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0027_remove_game_away_team_goalie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameevents',
            name='zone',
            field=models.IntegerField(choices=[(3, 'Attacking'), (1, 'Defending'), (2, 'Neutral')], default=1),
            preserve_default=False,
        ),
    ]
