# Generated by Django 5.2.6 on 2025-11-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0028_gameevents_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Started'), (2, 'Game in Progress'), (3, 'Game Over')], default=1),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='goal_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Short Handed'), (2, 'Normal'), (3, 'Power Play')], null=True),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='zone',
            field=models.IntegerField(blank=True, choices=[(1, 'Defending'), (2, 'Neutral'), (3, 'Attacking')], null=True),
        ),
    ]
