# Generated by Django 5.2.6 on 2025-11-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0029_alter_game_status_alter_gameevents_goal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevents',
            name='goal_type',
        ),
        migrations.RemoveField(
            model_name='gameevents',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='address_city',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='address_country',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='address_postal_code',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='address_region',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='address_street',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='analysis',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='birthplace_country',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='goals_against',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='height',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='jersey_number',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='losses',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='penalty_minutes',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='player_bio',
        ),
        # migrations.RemoveField(
        #     model_name='goalie',
        #     name='points',
        # ),
        migrations.RemoveField(
            model_name='goalie',
            name='power_play_goals_against',
        ),
        # migrations.RemoveField(
        #     model_name='goalie',
        #     name='save_percents',
        # ),
        migrations.RemoveField(
            model_name='goalie',
            name='saves',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='saves_above_avg',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='shoots',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='short_handed_goals_against',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='shots_on_goal',
        ),
        # migrations.RemoveField(
        #     model_name='goalie',
        #     name='shots_on_goal_per_game',
        # ),
        migrations.RemoveField(
            model_name='goalie',
            name='team',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='goalie',
            name='wins',
        ),
        migrations.RemoveField(
            model_name='player',
            name='assists',
        ),
        migrations.RemoveField(
            model_name='player',
            name='blocked_shots',
        ),
        migrations.RemoveField(
            model_name='player',
            name='faceoff_win_percents',
        ),
        migrations.RemoveField(
            model_name='player',
            name='faceoffs',
        ),
        migrations.RemoveField(
            model_name='player',
            name='faceoffs_won',
        ),
        migrations.RemoveField(
            model_name='player',
            name='five_on_five_diff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='player',
            name='goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='overall_diff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalties_drawn',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalty_kill_diff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='penalty_minutes',
        ),
        # migrations.RemoveField(
        #     model_name='player',
        #     name='points',
        # ),
        migrations.RemoveField(
            model_name='player',
            name='power_play_goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='power_play_goals_diff',
        ),
        migrations.RemoveField(
            model_name='player',
            name='scoring_chances',
        ),
        migrations.RemoveField(
            model_name='player',
            name='short_handed_goals',
        ),
        migrations.RemoveField(
            model_name='player',
            name='shots_on_goal',
        ),
        # migrations.RemoveField(
        #     model_name='player',
        #     name='shots_on_goal_per_game',
        # ),
        migrations.RemoveField(
            model_name='player',
            name='turnovers',
        ),
        migrations.AddField(
            model_name='goalie',
            name='player',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hockey.player'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GoalieTransaction',
        ),
    ]
