# Generated by Django 5.2.6 on 2025-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0030_remove_gameevents_goal_type_remove_gameevents_zone_and_more'),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle fields that may not exist in DB
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='goalie',
                    name='points',
                ),
                migrations.RemoveField(
                    model_name='goalie',
                    name='save_percents',
                ),
                migrations.RemoveField(
                    model_name='goalie',
                    name='shots_on_goal_per_game',
                ),
                migrations.RemoveField(
                    model_name='player',
                    name='points',
                ),
                migrations.RemoveField(
                    model_name='player',
                    name='shots_on_goal_per_game',
                ),
            ],
            database_operations=[
                # PostgreSQL supports IF EXISTS, so we can safely drop columns that may not exist
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE goalies DROP COLUMN IF EXISTS points;",
                        "ALTER TABLE goalies DROP COLUMN IF EXISTS save_percents;",
                        "ALTER TABLE goalies DROP COLUMN IF EXISTS shots_on_goal_per_game;",
                        "ALTER TABLE players DROP COLUMN IF EXISTS points;",
                        "ALTER TABLE players DROP COLUMN IF EXISTS shots_on_goal_per_game;",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
        migrations.AddField(
            model_name='gameevents',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('Normal', 'Normal'), ('Power Play', 'Power Play'), ('Short Handed', 'Short Handed')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gameevents',
            name='zone',
            field=models.CharField(blank=True, choices=[('Attacking', 'Attacking'), ('Defending', 'Defending'), ('Neutral', 'Neutral')], max_length=20, null=True),
        ),
    ]
