# Generated by Django 5.2.6 on 2025-11-03 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0031_remove_goalie_points_remove_goalie_save_percents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevents',
            name='number',
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='goalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.goalie'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player', to='hockey.player'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='player_2', to='hockey.player'),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='shot_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.shottype'),
        ),
    ]
