# Generated by Django 5.2.6 on 2025-11-03 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0032_remove_gameevents_number_alter_gameevents_goalie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamegoalie',
            name='start_period',
        ),
        migrations.RemoveField(
            model_name='gamegoalie',
            name='start_time',
        ),
        migrations.AddField(
            model_name='game',
            name='away_goalies',
            field=models.ManyToManyField(related_name='away_games', to='hockey.goalie'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_players',
            field=models.ManyToManyField(related_name='away_games', to='hockey.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_start_goalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='away_start_games', to='hockey.goalie'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_goalies',
            field=models.ManyToManyField(related_name='home_games', to='hockey.goalie'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_players',
            field=models.ManyToManyField(related_name='home_games', to='hockey.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_start_goalie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='home_start_games', to='hockey.goalie'),
        ),
    ]
