# Generated by Django 5.2.6 on 2025-11-04 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0033_remove_gamegoalie_start_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_type_group',
        ),
    ]
