# Generated by Django 5.2.6 on 2025-11-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0034_remove_game_game_type_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlightreel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='highlightreel',
            name='game_events',
            field=models.ManyToManyField(related_name='highlight_reels', to='hockey.gameevents'),
        ),
        migrations.AddField(
            model_name='highlightreel',
            name='user_email',
            field=models.CharField(default='test@test.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlightreel',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
