# Generated by Django 5.2.6 on 2025-11-05 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0035_remove_highlightreel_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_actual', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tournament_names',
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='tournament_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.tournamentname'),
        ),
    ]
