# Generated by Django 5.2.6 on 2025-11-05 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0036_tournamentname_alter_game_tournament_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournament_name',
        ),
        migrations.CreateModel(
            name='GameTypeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('is_actual', models.BooleanField(default=True)),
                ('game_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.gametype')),
            ],
            options={
                'db_table': 'game_type_names',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='game_type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.gametypename'),
        ),
        migrations.DeleteModel(
            name='TournamentName',
        ),
    ]
