# Generated by Django 5.2.6 on 2025-11-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0037_remove_game_tournament_name_gametypename_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gametypename',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AddConstraint(
            model_name='gametypename',
            constraint=models.UniqueConstraint(fields=('game_type', 'name'), name='unique_game_type_name'),
        ),
    ]
