# Generated by Django 5.2.6 on 2025-11-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0038_alter_gametypename_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameperiod',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
