# Generated by Django 5.2.6 on 2025-11-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0039_gameperiod_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameperiod',
            name='order',
            field=models.IntegerField(unique=True),
        ),
    ]
