# Generated by Django 5.2.6 on 2025-11-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0040_alter_gameperiod_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerposition',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
