# Generated by Django 5.2.6 on 2025-11-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0041_alter_playerposition_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameevents',
            name='is_faceoff_won',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hockey.team'),
        ),
    ]
