# Generated by Django 5.2.6 on 2025-11-10 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0042_remove_gameevents_is_faceoff_won_alter_player_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=150)),
                ('note', models.TextField()),
                ('youtube_link', models.CharField(blank=True, max_length=1000, null=True, verbose_name='YouTube Link')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('user_email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'custom_events',
            },
        ),
        migrations.RemoveField(
            model_name='highlightreel',
            name='game_events',
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('user_email', models.CharField(max_length=255)),
                ('custom_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='highlights', to='hockey.customevents')),
                ('game_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='hockey.gameevents')),
                ('highlight_reel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='hockey.highlightreel')),
            ],
            options={
                'db_table': 'highlights',
            },
        ),
    ]
