# Generated by Django 5.2.6 on 2025-11-11 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0043_customevents_remove_highlightreel_game_events_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='custom_event',
        ),
        migrations.AddField(
            model_name='customevents',
            name='highlight',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_event', to='hockey.highlight'),
        ),
    ]
