# Generated by Django 5.2.6 on 2025-11-11 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0044_remove_highlight_custom_event_customevents_highlight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevents',
            name='highlight',
        ),
        migrations.AddField(
            model_name='highlight',
            name='custom_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='highlights', to='hockey.customevents'),
        ),
    ]
