# Generated by Django 5.2.6 on 2025-11-11 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0045_remove_customevents_highlight_highlight_custom_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='custom_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='highlights', to='hockey.customevents'),
        ),
    ]
