# Generated by Django 5.2.6 on 2025-11-11 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0046_alter_highlight_custom_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playertransaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hockey.team'),
        ),
    ]
