# Generated by Django 5.2.6 on 2025-11-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0047_player_is_archived_alter_playertransaction_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
