# Generated by Django 5.2.6 on 2025-11-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0048_team_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlightreel',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
