# Generated by Django 5.2.6 on 2025-11-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0049_highlightreel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customevents',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
