# Generated by Django 5.2.6 on 2025-11-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0050_customevents_user_id_highlight_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customevents',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='highlightreel',
            name='user_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
