# Generated by Django 5.2.6 on 2025-11-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0051_alter_customevents_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customevents',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='highlight',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='highlightreel',
            name='user_email',
        ),
        migrations.AlterField(
            model_name='customevents',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlight',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='highlightreel',
            name='user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
