# Generated by Django 5.2.6 on 2025-11-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0052_remove_customevents_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('youtube_link', models.CharField(max_length=1000, verbose_name='YouTube Link')),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'video_library',
            },
        ),
    ]
