# Generated by Django 5.2.6 on 2025-11-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0053_videolibrary'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
