# Generated by Django 5.2.6 on 2025-11-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0054_team_abbreviation'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='blocked_shots',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameevents',
            name='goal_type',
            field=models.CharField(blank=True, choices=[('Even Strength', 'Even Strength'), ('Power Play', 'Power Play'), ('Short Handed', 'Short Handed')], max_length=20, null=True),
        ),
    ]
