# Generated by Django 5.2.6 on 2025-11-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0055_game_analysis_gameplayer_blocked_shots_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='gameeventsanalysisqueue',
            name='unique_game_event_game_action',
        ),
        migrations.RemoveField(
            model_name='game',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='gameevents',
            name='is_deprecated',
        ),
        migrations.RemoveField(
            model_name='gameeventsanalysisqueue',
            name='action',
        ),
        migrations.RemoveField(
            model_name='gameeventsanalysisqueue',
            name='game',
        ),
        migrations.RemoveField(
            model_name='gameeventsanalysisqueue',
            name='game_event',
        ),
        migrations.AddField(
            model_name='gameeventsanalysisqueue',
            name='payload',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gameeventsanalysisqueue',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
