# Generated by Django 5.2.6 on 2025-11-21 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0056_remove_gameeventsanalysisqueue_unique_game_event_game_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='faceoffs_won',
            field=models.IntegerField(default=0),
        ),
    ]
