# Generated by Django 5.2.6 on 2025-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0057_gameplayer_faceoffs_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='power_play_goals',
            field=models.IntegerField(default=0, verbose_name='PPG'),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='short_handed_goals',
            field=models.IntegerField(default=0, verbose_name='SHG'),
        ),
    ]
