# Generated by Django 5.2.6 on 2025-11-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0058_gameplayer_power_play_goals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoalie',
            name='power_play_goals_against',
            field=models.IntegerField(default=0, verbose_name='PPGA'),
        ),
        migrations.AddField(
            model_name='gamegoalie',
            name='short_handed_goals_against',
            field=models.IntegerField(default=0, verbose_name='SHGA'),
        ),
    ]
