# Generated by Django 5.2.6 on 2025-11-21 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0059_gamegoalie_power_play_goals_against_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goalieseason',
            name='save_percents',
        ),
    ]
