# Generated by Django 5.2.6 on 2025-11-21 19:27

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0060_remove_goalieseason_save_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalieseason',
            name='save_percents',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('saves__gt', 0), ('goals_against__gt', 0), _connector='OR'), then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('saves'), '/', django.db.models.expressions.CombinedExpression(models.F('saves'), '+', models.F('goals_against'))), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Save %'),
        ),
    ]
