# Generated by Django 5.2.6 on 2025-11-21 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0061_goalieseason_save_percents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerseason',
            name='faceoff_win_percents',
        ),
    ]
