# Generated by Django 5.2.6 on 2025-11-21 19:30

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0062_remove_playerseason_faceoff_win_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerseason',
            name='faceoff_win_percents',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(faceoffs__gt=0, then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('faceoffs_won'), '/', models.F('faceoffs')), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Faceoff Win %'),
        ),
    ]
