# Generated by Django 5.2.6 on 2025-11-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0063_playerseason_faceoff_win_percents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('status', models.CharField(blank=True, max_length=150, null=True)),
                ('last_finished', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('log', models.TextField(default='')),
            ],
            options={
                'db_table': 'processes_status',
            },
        ),
    ]
