# Generated by Django 5.2.6 on 2025-11-26 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0064_processstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='penalties_drawn',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
