# Generated by Django 5.2.6 on 2025-11-26 21:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0065_gameplayer_penalties_drawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoalie',
            name='penalty_minutes',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
