# Generated by Django 5.2.6 on 2025-11-27 15:29

import datetime
import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0066_gamegoalie_penalty_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalieTeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shots_on_goal', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('penalty_minutes', models.DurationField(default=datetime.timedelta(0))),
                ('short_handed_goals_against', models.IntegerField(default=0, verbose_name='SHGA')),
                ('power_play_goals_against', models.IntegerField(default=0, verbose_name='PPGA')),
                ('save_percents', models.GeneratedField(db_persist=True, expression=models.Case(models.When(models.Q(('saves__gt', 0), ('goals_against__gt', 0), _connector='OR'), then=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('saves'), '/', django.db.models.expressions.CombinedExpression(models.F('saves'), '+', models.F('goals_against'))), '*', models.Value(100))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField(), verbose_name='Save %')),
                ('shots_on_goal_per_game', models.GeneratedField(db_persist=True, expression=models.Case(models.When(games_played__gt=0, then=django.db.models.expressions.CombinedExpression(models.F('shots_on_goal'), '/', models.F('games_played'))), default=models.Value(0), output_field=models.FloatField()), output_field=models.FloatField())),
                ('points', models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(models.F('goals'), '+', models.F('assists')), output_field=models.IntegerField())),
                ('goalie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockey.goalie')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='hockey.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hockey.team')),
            ],
            options={
                'db_table': 'goalie_team_seasons',
            },
        ),
    ]
