# Generated by Django 5.2.6 on 2025-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0067_goalieteamseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamegoalie',
            name='shots_on_goal',
            field=models.IntegerField(default=0),
        ),
    ]
