# Generated by Django 5.2.6 on 2025-11-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0069_remove_gamegoalie_shots_against_playerteamseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalieseason',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goalieteamseason',
            name='ties',
            field=models.IntegerField(default=0),
        ),
    ]
