# Generated by Django 5.2.6 on 2025-12-03 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0070_goalieseason_ties_goalieteamseason_ties'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'Private'), (2, 'Restricted'), (3, 'Public')], default=1),
        ),
        migrations.CreateModel(
            name='HighlightUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_access', to='hockey.highlight')),
            ],
            options={
                'db_table': 'highlight_user_access',
            },
        ),
    ]
