# Generated by Django 5.2.6 on 2025-12-09 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0071_highlight_visibility_highlightuseraccess'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['-date'], name='idx_games_date_desc'),
        ),
    ]
