# Generated by Django 5.2.6 on 2025-12-16 16:25

import django.db.models.deletion
from django.db import migrations, models


def populate_age_groups(apps, schema_editor):
    """Populate TeamAgeGroup with unique age groups from Team table."""
    Team = apps.get_model('hockey', 'Team')
    TeamAgeGroup = apps.get_model('hockey', 'TeamAgeGroup')
    
    # Get all unique age groups from Team table
    age_groups = Team.objects.values_list('age_group', flat=True).distinct()
    
    # Create TeamAgeGroup entries for each unique age group
    for age_group in age_groups:
        if age_group:  # Skip None/empty values
            TeamAgeGroup.objects.get_or_create(name=age_group)


def migrate_team_age_groups(apps, schema_editor):
    """Migrate Team.age_group from CharField to ForeignKey."""
    Team = apps.get_model('hockey', 'Team')
    TeamAgeGroup = apps.get_model('hockey', 'TeamAgeGroup')
    
    # Update each team's age_group field to reference the TeamAgeGroup
    for team in Team.objects.all():
        if team.age_group_old:
            age_group_obj = TeamAgeGroup.objects.get(name=team.age_group_old)
            team.age_group = age_group_obj
            team.save(update_fields=['age_group'])


def reverse_migrate_team_age_groups(apps, schema_editor):
    """Reverse migration: Copy ForeignKey values back to CharField."""
    Team = apps.get_model('hockey', 'Team')
    
    # Copy age_group ForeignKey name back to age_group_old CharField
    for team in Team.objects.all():
        if team.age_group:
            team.age_group_old = team.age_group.name
            team.save(update_fields=['age_group_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0072_game_idx_games_date_desc'),
    ]

    operations = [
        # Step 1: Create TeamAgeGroup table with integer primary key
        migrations.CreateModel(
            name='TeamAgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'db_table': 'team_age_groups',
            },
        ),
        
        # Step 2: Populate TeamAgeGroup with unique values from Team.age_group
        migrations.RunPython(populate_age_groups, reverse_code=migrations.RunPython.noop),
        
        # Step 3: Rename old age_group field
        migrations.RenameField(
            model_name='team',
            old_name='age_group',
            new_name='age_group_old',
        ),
        
        # Step 4: Make age_group_old nullable (for safe rollback)
        migrations.AlterField(
            model_name='team',
            name='age_group_old',
            field=models.CharField(max_length=5, null=True, blank=True),
        ),
        
        # Step 5: Add new age_group as ForeignKey (nullable temporarily)
        migrations.AddField(
            model_name='team',
            name='age_group',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.RESTRICT,
                to='hockey.teamagegroup'
            ),
        ),
        
        # Step 6: Migrate data from age_group_old to age_group
        migrations.RunPython(migrate_team_age_groups, reverse_code=reverse_migrate_team_age_groups),
        
        # Step 7: Remove old field
        migrations.RemoveField(
            model_name='team',
            name='age_group_old',
        ),
        
        # Step 8: Make age_group non-nullable
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to='hockey.teamagegroup'
            ),
        ),
    ]
