# Generated by Django 5.2.6 on 2026-03-04 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0073_teamagegroup_alter_team_age_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=150)),
                ('analysis', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('user_id', models.IntegerField()),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hockey.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hockey.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hockey.team')),
            ],
            options={
                'db_table': 'analytics',
                'unique_together': {('author', 'date', 'time', 'team', 'player', 'game')},
            },
        ),
    ]
