# Generated by Django 5.2.6 on 2026-03-05 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0074_analytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('analytics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_with_access', to='hockey.analytics')),
            ],
            options={
                'db_table': 'analytics_user_access',
            },
        ),
    ]
