# Generated by Django 5.2.6 on 2026-03-09 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0075_analyticsuseraccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTryout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Cut', 'Cut'), ('Made Team', 'Made Team'), ('Trying Out', 'Trying Out')], max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'player_tryouts',
            },
        ),
        migrations.RemoveConstraint(
            model_name='team',
            name='unique_team',
        ),
        migrations.AlterUniqueTogether(
            name='analytics',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='playertransaction',
            name='previous_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertransaction',
            name='previous_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_from', to='hockey.team'),
        ),
        migrations.AddField(
            model_name='team',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertransaction',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='playertransaction',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playertransaction',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hockey.team'),
        ),
        migrations.AddConstraint(
            model_name='analytics',
            constraint=models.UniqueConstraint(fields=('author', 'date', 'time', 'team', 'player', 'game'), name='unique_analytics'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('name', 'birth_year', 'city'), name='unique_team'),
        ),
        migrations.AddField(
            model_name='playertryout',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryouts', to='hockey.player'),
        ),
        migrations.AddField(
            model_name='playertryout',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tryouts', to='hockey.team'),
        ),
    ]
