# Generated by Django 5.2.6 on 2026-03-10 11:59

import django.db.models.deletion
import hockey.utils.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0076_playertryout_remove_team_unique_team_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTryoutStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(hockey.utils.constants.PlayerTryoutStatus['CUT'], hockey.utils.constants.PlayerTryoutStatus['CUT']), (hockey.utils.constants.PlayerTryoutStatus['MADE_TEAM'], hockey.utils.constants.PlayerTryoutStatus['MADE_TEAM']), (hockey.utils.constants.PlayerTryoutStatus['TRYING_OUT'], hockey.utils.constants.PlayerTryoutStatus['TRYING_OUT'])], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'player_tryout_status_history',
            },
        ),
        migrations.AddField(
            model_name='playertryout',
            name='changed_at',
            field=models.DateTimeField(default='2026-03-10 11:48:00 +00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertryout',
            name='changed_by',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playertryout',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playertryout',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='playertryout',
            constraint=models.UniqueConstraint(fields=('player', 'team'), name='unique_player_tryout'),
        ),
        migrations.AddField(
            model_name='playertryoutstatushistory',
            name='player_tryout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='hockey.playertryout'),
        ),
    ]
