# Generated by Django 5.2.6 on 2026-03-10 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hockey', '0077_playertryoutstatushistory_playertryout_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hockey.game'),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='hockey.player'),
        ),
    ]
