# Generated by Django 5.2.6 on 2025-10-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='save_percents',
            field=models.IntegerField(blank=True, null=True, verbose_name='save %'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, verbose_name='postal/zip code'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street',
            field=models.CharField(blank=True, max_length=200, verbose_name='street'),
        ),
    ]
