# Generated by Django 5.2.6 on 2025-10-11 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_save_percents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='save_percents',
        ),
    ]
