# Generated by Django 5.2.6 on 2025-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_customuser_save_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Coach'), (3, 'Player')], default=3, verbose_name='Website role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='team_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Team'),
        ),
    ]
