# Generated by Django 5.2.6 on 2026-03-05 20:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_role_customuser_team_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('invited_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invitation_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invitation_details', models.JSONField(blank=True, null=True)),
                ('send_email_error_message', models.TextField(blank=True, null=True)),
                ('send_email_error_traceback', models.TextField(blank=True, null=True)),
                ('send_email_error_timestamp', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_invitation',
                'unique_together': {('email', 'invited_by', 'invitation_details')},
            },
        ),
    ]
