# Generated by Django 5.2.6 on 2026-03-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userinvitation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userinvitation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='userinvitation',
            constraint=models.UniqueConstraint(fields=('email', 'invited_by', 'invitation_details'), name='unique_user_invitation'),
        ),
    ]
