# Generated by Django 5.2.6 on 2026-03-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userinvitation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gamesheet_seasonid',
            field=models.TextField(blank=True, null=True, verbose_name='Gamesheet season ID'),
        ),
    ]
